### PR TITLE
Collapsible filters

### PR DESCRIPTION
**Pull request by Kinlaw**
This implements collapsible filters across insights in the various views where local filters already existed.

Modules affected:
- Actions
- Inventory
- Planner
- Rules

Other changes:
- Removes productFilters because they are no longer in use.
- Removes multi-state filters in favor of dropdown filters.
- Adds headers to each module.

### CODE REVIEW

**Comment by jharting** [comment]
\<nitpicking\> I think that too much white space is used on the actions page now:

Before:
before
After:
after

**Comment by Kinlaw** [comment]
I think that's a fair point. Fixing...

**Comment by iphands** [comment]
To further nitpick... @mattnolting does not have to change now, but since you are requiring a header on all pages now, could you mock up a more slender and sleek header?

**Comment by jharting** [comment]
@Kinlaw there seems to be a regression in planner's URL handling. Before e.g. https://prod.foo.redhat.com:1337/insightsbeta/planner/28325 would open up the specific plan whereas now it does not do that any longer

**Comment by mattnolting** [comment]
@iphands working on sleek headers now.. they'll go into page filters release

**Comment by iphands** [comment]
@Kinlaw unti tests failing, looks like a simple string change update in test is needed.

**Comment by Kinlaw** [comment]
Fixing scrollToPlan functionality and unit tests.

**Comment by mattnolting** [comment]
@iphands @jharting @Kinlaw I restyled the headers, re-styled the table search and table/card view positioning and fixed several odd spacing issues.

**Pull request merged**
