### PR TITLE
Adding back to CP and logout buttons to navigation

### PR DESCRIPTION
**Pull request by mattnolting**
Can @Kinlaw @iphands one of you fellas wire these buttons up?

### CODE REVIEW

**Comment by mattnolting** [comment]
screen shot 2018-01-23 at 9 18 27 am

**Comment by mattnolting** [comment]
screen shot 2018-01-23 at 9 19 54 am

**Comment by iphands** [comment]
The hrefs should just be "/" and "/logout"

**Comment by iphands** [comment]
Welll /logout might be more complicated. Asking the Portal dudes meow :cat:

**Comment by mattnolting** [comment]
screen shot 2018-01-23 at 9 31 50 am

**Comment by mattnolting** [comment]
screen shot 2018-01-23 at 9 41 09 am

**Comment by iphands** [comment]
I think after ^ is fixed it looks ready to go. @Kinlaw or @jharting interested in your review of the InsightsJwt thing I created though.

**Comment by mattnolting** [comment]
@iphands Should be ready to go. The logout icon could easily be confused with 'minimize nav,' so I added text and stacked the buttons.

**Comment by iphands** [comment]
@mattnolting mine still looks grayed out.. as if it is disabled

**Comment by iphands** [comment]
Why is the color 4c4c4c in this case?

**Comment by iphands** [comment]
Oh its because "white" is only applied to `.primary-nav a`

**Comment by iphands** [comment]
Wait... nvm... needed to pull :D

**Comment by iphands** [comment]
@Kinlaw this feature looks good to me, but I'll hold off merging until you take a look at the JS changes I made.

**Pull request merged**
