### PR TITLE
ansible-icon improvements

### PR DESCRIPTION
**Pull request by jharting**
https://github.com/RedHatInsights/insights-frontend/issues/100
https://trello.com/c/Tw1LEhHO/113-review-ansible-icon-tooltips

### CODE REVIEW

**Comment by iphands** [comment]
Hey does this add an alt tag for icons that have to tooltip?
We still need an icon there. Maybe tooltip || 'Ansible Playbook available' ?

**Comment by jharting** [comment]
@iphands I don't entirely follow the comment. The way it works currently is that alt="" is set in those places where tooltip is shown. The value of alt and tooltip is the same. There are a few places where no tooltip neither alt is needed IMHO, e.g:

**Comment by iphands** [comment]
No I think the initial request is meant for visually impaired folks who are using screen readers. In that case the alt tag should have some default messaging.

To be HTML four standards-compliant at least every single image regardless of purpose would have an alt the tag. I know we are HTML5 but just saying (the HTML5 validator might actually require an Ulta tag on images also).

Can we provide a default alt value for this ansible image whenever a tooltip is not available?

**Comment by jharting** [comment]
@iphands 

I see. The [w3c guidelines for alt attribute](https://www.w3schools.com/tags/att_img_alt.asp) say:

> * Use alt="" if the image is only for decoration

The only places where the tooltip is not available is the Actions dropdown items (see screenshots above). I am no expert on usability but I think these cases qualify for "only for decoration" (the link is pretty descriptive even without the logo) Therefore, I am tempted to leave the alt attribute empty. Alternatively, I can add something like `alt="Ansible logo"`

WDYT?

**Comment by iphands** [comment]
> can add something like alt="Ansible logo"

I think that would suffice. I would consider having the alt in that case say something like "Ansible Playbook support" or "has ..."

In the fewest amount of words, what do you think that icon conveys to a user. What would you want a blind person to know/understand when they hear "Ansible logo"?

I think in "Use alt="" if the image is only for decoration" "decoration" is slightly taken out of context here.
We are using the icon for decoration that is true, but it is not purely for eye pleasing aesthetics, we really are trying to tell the user something.

**Comment by iphands** [comment]
@Kinlaw :( we were still working on this one :(

**Comment by Kinlaw** [comment]
Whoops. My bad guys. I didn't read the comments, just saw my name as the reviewer and clicked the button.

**Pull request merged**
