### PR TITLE
Add the static assets as a Git submodule.

### PR DESCRIPTION
**Pull request by iphands**
We can do this now that the assets are all under static/
See the updated README.md for tips.

### CODE REVIEW

**Comment by iphands** [comment]
Looks like I need to update travis to not pull that submodule.
Really travis it not used for anything. These days Jenkins runs the unit tests... still I like having Travis because it finishes sooner, and we could get a faster report on the unit tests.

**Comment by jharting** [comment]
This looks broken. After `git submodule update` the file paths look like: `static/static/images/bg_ansible.jpg` instead of expected `static/images/bg_ansible.jpg`

**Comment by iphands** [comment]
Sorry, pull the latest assets. I moved everything to the root of the repo.

**Comment by jharting** [comment]
@iphands I still see the same :-(

**Comment by jharting** [comment]
@iphands oh wait, my bad

**Pull request merged**
