### PR TITLE
planner - system reboot handling

### PR DESCRIPTION
**Pull request by jharting**

### CODE REVIEW

**Comment by jharting** [comment]
Depends on http://labs-git.usersys.redhat.com/labs/telemetryapi/merge_requests/423

**Comment by ryelo** [comment]
@jharting Changed the styling of the tabs, reformatted how the tabs should work. Changed the layout of the buttons at the bottom of each plan to clean up the code. Changed resolution modal to have the restart icon and text on the next line.

**Comment by jharting** [comment]
@ryelo looks perfect except for



is the reboot indication looks expected?

**Comment by ryelo** [comment]
@jharting fixing!

**Comment by jharting** [comment]
@iphands @Kinlaw the API and migrated playbooks are in place. This is not ready for review.

**Comment by jharting** [comment]
@Kinlaw yes, that pop up was intentionally replaced by the "checkbox" at the bottom of the playbook tab. Any ideas on how to address this without re-introducing it?

**Pull request merged**
