### PR TITLE
Enhancements/incidents lite

### PR DESCRIPTION
**Pull request by mattnolting**
Please check it out, lemme know if there are issues or it's ugly

### CODE REVIEW

**Comment by Kinlaw** [comment]
@mattnolting this looks nearly identical to the incidents summary on the actions page. I thought we were going with something lighter on the overview page? #139

**Comment by mattnolting** [comment]
@Kinlaw mr kinlaw, need help getting the total issue count to render

**Comment by Kinlaw** [comment]
@mattnolting I hooked you up and moved incidentsLite to be under components -> incidents.

The text on the right is rubbing up on the divider in the box. Do you mind taking a look at it?
screen shot 2017-10-16 at 2 17 23 pm

**Comment by mattnolting** [comment]
@Kinlaw Revised

**Comment by Kinlaw** [comment]
@jharting can you or @iphands review this one since I contributed a good portion of the code to this PR?

**Comment by iphands** [comment]
@mattnolting can we stop putting underscores on all the scss?

**Comment by iphands** [comment]
Also if we have:
`incidentSummary.directive.js`
`incidentSummary.jade`

I think `_incident-summary.scss` is bad. We should just stick with the camelCaseConvention

**Comment by mattnolting** [comment]
@iphands No, underscores denote partial scss files. Naming the files with dashes matches the component/module selector and follows our css naming conventions. https://smacss.com/book/html5. We don't use camelcase in css for several reasons, most importantly bc it's harder to read..

**Comment by Kinlaw** [comment]
@iphands I moved the incident-lite js logic into incidentLite.directive.js. Should be good to go.

**Pull request merged**
