### PR TITLE
Fixes/update most deps

### PR DESCRIPTION
**Pull request by iphands**
Skipping Angular for now... we might need to coordinate the upgrade to 1.6.x with @lphiri

### CODE REVIEW

**Comment by jharting** [comment]
The only regression I found is that ui-select is too tall
screenshot_20180129_100838

**Comment by mattnolting** [comment]
Updated css to fix dropdown height

**Comment by jharting** [comment]
I fixed the sweetAlert regression

**Comment by Kinlaw** [comment]
When creating a new plan the "Add to existing plan" dropdown text floats off of the modal.

screen shot 2018-02-01 at 2 29 09 pm

**Comment by Kinlaw** [comment]
When creating a new plan the table headers for the actions table have white backgrounds on a gray background.

screen shot 2018-02-01 at 2 31 37 pm

**Comment by Kinlaw** [comment]
C3 PR for fixing the 360 gauge on the overview goals widget has been accepted. Just waiting for the merge and build.

https://github.com/c3js/c3/pull/2282

**Comment by Kinlaw** [comment]
c3 PR merged https://github.com/c3js/c3/releases/tag/v0.4.20

**Comment by iphands** [comment]
Cool so we can merge this now? Any objections?

**Comment by iphands** [comment]
@Kinlaw that regression exists on stable too I think

**Pull request merged**
