### PR TITLE
Stop using replace:true in directives

### PR DESCRIPTION
**Pull request by iphands**

### CODE REVIEW

**Comment by iphands** [comment]
Im not sure if this is ready to use with Edge and Firefox, but lets check.

**Comment by Kinlaw** [comment]
Things that I noticed in Chrome:

Incident and Risk Summary styling is off

screen shot 2017-10-17 at 4 01 03 pm

Featured Topics are off

screen shot 2017-10-17 at 4 02 13 pm

Card view is off on actions page 3 and inventory

screen shot 2017-10-17 at 4 03 25 pm

The boxes inside of the playbook view in planner

screen shot 2017-10-17 at 4 05 02 pm

**Comment by jharting** [comment]
why are we doing this?

**Comment by iphands** [comment]
@jharting not a prio or necessary... but long term we would like to start having the directives we build emit custom elements on the page. At that point the HTML becomes much more semantically meaningful.

Also longer term I would like for us to move to Polymer for web components (or something that properly uses shadow dom components + custom tags).

**Pull request closed without merging**
