### PR TITLE
search functionality for group selection in global filters

### PR DESCRIPTION
**Pull request by jeudy100**
group-filter-1
group-filter-2

enhancement for issue #138

### CODE REVIEW

**Comment by Kinlaw** [comment]
#138

**Comment by Kinlaw** [comment]
The filtering looks good.

One thing that I was expecting as a user is that when I am typing in the search bar, I would expect there to be a way for me to select one of the search results with the keyboard. Intuitively I expect to be able to just hit the down arrow and select one of the results but I would settle for hitting tab and then down. Currently there is no way to select any of the search options without using the mouse.

Also, for some reason executive reports is broken in this PR. It works in master so I'm not sure what's going on.
screen shot 2017-08-29 at 4 07 48 pm

**Comment by Kinlaw** [comment]
A nice to have would be to be able to close the group select by hitting esc but it's definitely not a blocker.

**Comment by jeudy100** [comment]
@Kinlaw added both selection by arrow keys and esc closes dropdown and executive reports works on my machine.
executivereports

**Pull request merged**
