### PR TITLE
Added esc navigation to actions rule page

### PR DESCRIPTION
**Pull request by jeudy100**
**issue #345** 

gifrecord_2018-01-03_125928
gifrecord_2018-01-03_125732

### CODE REVIEW

**Comment by jharting** [comment]
@jeudy100 note that there are existing pieces of code in the codebase that we should be reusing. 
To suppress esc navigation when a modal is open use https://github.com/RedHatInsights/insights-frontend/blob/master/app/js/services/modalUtils.js#L10
There is already a component for handling esc navigation on actions pages: https://github.com/RedHatInsights/insights-frontend/blob/master/app/js/components/actions/actionsBack/actionsBack.directive.js

**Comment by jeudy100** [comment]
gifrecord_2018-01-05_091426
gifrecord_2018-01-05_091635

**Comment by jeudy100** [comment]
@jharting I did not suppress the escape event when you close the modal, but I have it working now.

gifrecord_2018-01-05_111942

**Comment by jharting** [comment]
@jeudy100 thanks for the fix. I'm leaving https://github.com/RedHatInsights/insights-frontend/issues/345 open to track the second part, which is adding this behavior to other parts of insights frontend that have similar navigational hierarchy (e.g. policies). Feel free to work on that also.

**Pull request merged**
