### PR TITLE
Policies/cards standardizing

### PR DESCRIPTION
**Pull request by mattnolting**
- abstracted states
- added a sub-title to header
- fixed various fitting issues in the modal
- put card styles into the card component 
- split card-header, card-content, card-footer out into individual files

### CODE REVIEW

**Comment by iphands** [comment]
Shares many changes with #379 ... waiting for that to merge so that we can rebase this on top of #379 once #379 hits master.

**Comment by ryelo** [comment]
Is this not just the squashed version of #379 ?

**Comment by iphands** [comment]
@jharting Closed #379 to switch to this PR... can you have a quick look at the otb's for meh?

**Comment by jharting** [comment]
Also, opening the system modal e.g. from the actions page used to bring up the system model with the given rule being first and expanded (others retracted). With this PR the rule is first but no longer expanded

**Comment by iphands** [comment]
@jharting @Kinlaw So I am interested in your thoughts here.

I went in and made ruleSummaries work with cards as it had before, and rm'ed ruleSummary.
BUT I am not 100% sure I like the merged directives. On one hand I do, because the ruleSummary was only used in one place... on the other hand it felt weird working on it as one big thing.

I want you opinion here. I think if we go back to a split scenario... we should rename each directive.
Something like:
```html
<modal-rule-list>
  <modal-rule>
   <card/>
  </modal-rule>
  <modal-rule>
   <card/>
  </modal-rule>
</modal-rule-list>
```
???

**Comment by jharting** [comment]
@iphands I don't have a strong preference. Normally I am for splitting things into components which keeps things clean and readable however in this case the components are very simple so I can live fine with one of those layers merged.

Should the naming scheme say 'system-modal-rule-summaries' though? We have many different modals where rules are displayed.

**Comment by Kinlaw** [comment]
@iphands I'm fine with them being merged as well. 

@jharting system-modal-rule-summaries seems a little long. What if we nest rule-summaries under the system-modal directive?

**Comment by mattnolting** [comment]
@Kinlaw I love it. I think <system-modal> should be abstracted as well.
- system-modal
-- meta
-- policies
-- rules
-- the-next-tab
-- another-modal-component

**Comment by iphands** [comment]
@Kinlaw I think the main reason for breaking them apart is if we can start to write generic list handler components.

If we had a reusable list generic that had common logic for expand/collapse all, pagination, etc. Then it makes a lot of sense to split.

Even if things are not share though I do prefer the DOM when I see `<list><rules/></list>`... I think we all like that mo betta

**Comment by mattnolting** [comment]
@iphands @Kinlaw @iphands To clarify, I want to be able to find files, meaning i want the directory to match the component name. So I want <list> to be inside directory list and <rules> to be inside directory rules. And <list-rules>, if that exists, to be inside list-rules dir. And for the naming convention to be dash notation, rather than camelCase.. That's all a brotha wants...

**Comment by Kinlaw** [comment]
@iphands that's a good point. It would be nice to have a generic list handler.

**Comment by iphands** [comment]
Matt if we simply stop using replace: true on directive it will be stupid easy to find the file you're looking for.

We should still do a better job of sorting things in the folder hierarchy for simple browseability when you don't actually want to use a find/search

I think the biggest issue we have right now is that the thing you look at in the Dom it's not necessarily have the directive name in it, and thus you have to go searching for structures that are unique in the Jade to find what you're looking for.

Let's talk more about this after scrum on Monday please. I have some ideas and i too would like to make this better.

**Comment by iphands** [comment]
@mattnolting @Kinlaw @ryelo 

Closing this based on the discussion about whether or not it was good to merge the list and items code in the first place.

Not deleting the branch... if you feel strongly lets re open, argue, and merge.

**Pull request closed without merging**
