### PR TITLE
ansible integration: store resolution preference (phase 2)

### PR DESCRIPTION
**Pull request by jharting**
Switches from generating playbooks to downloading playbooks. Ambiguity is no longer dealt with maintenancePlaybook modal.
Instead, a playbook is by default downloadable. Resolutions can be modified from the playbook tab.

https://trello.com/c/XXvmEmTx/115

### CODE REVIEW

**Comment by jharting** [comment]
http://labs-git.usersys.redhat.com/labs/telemetryapi/merge_requests/406

**Comment by jharting** [comment]
@Kinlaw the API is in place. This is not ready for review.

**Comment by jharting** [comment]
@Kinlaw Oops, I meant "now ready" but instead wrote "not ready". Anyhow, this should be ready now.

**Comment by Kinlaw** [comment]
The code and functionality look solid. 

To me it seems like it would be easy to miss the ability to modify the ansible resolution without training which is something that our users don't typically seem to have. What was the drive to move away from the wizard (step-by-step) process?

**Comment by jharting** [comment]
@Kinlaw good point. I'll ask @mattnolting for help making the modify option more noticeable.

As for the motivations two things changed since the initial version:
1. The process of choosing from multiple resolutions is no longer mandatory - e.g. you can always just hit "download playbook" and you'll get one - no questions asked
2. We store your preference so it's no longer generating a playbook based on your current preference but rather changing the plan.

The wizard is gone especially because of (2) since now when you change your mind about a specific rule we do not want to force you to next-click the entire wizard again (with possibly a dozen or more steps). Having an option to change resolution for that particular rule directly is more useful IMHO.

**Comment by Kinlaw** [comment]
@jharting I can go ahead and merge it in. This is better than the wizard since we are storing the user's preferences and we can always iterate on it.

**Pull request merged**
