### PR TITLE
planner - prompt about ansible resolutions upfront

### PR DESCRIPTION
**Pull request by jharting**
https://trello.com/c/3Bam0zVR/118-prompt-user-about-multi-resolution-rules-upfront-first-time-they-add-a-rule-to-the-plan

### CODE REVIEW

**Comment by jharting** [comment]
@Kinlaw found a glitch in this MR. Putting the MR on hold temporarily.

**Comment by jharting** [comment]
@iphands @Kinlaw Fixed the bug. Not entirely happy about the wording of the "Use defaults" button - input appreciated.

What the button does is that it lets you skips all further resolution selection questions - while at the same time all those you already answered at that point (if any) will be saved.

**Comment by Kinlaw** [comment]
@jharting it looks good overall. I agree the wording of the "Use defaults" button doesn't seem quite right but I'm not sure I have anything better. Maybe "Skip" or "Skip All (rule_count)". My hesitation with the "Skip All" wording is that skip implies that no action is being taken when in reality we are still setting the resolutions.

**Comment by iphands** [comment]
@Kinlaw that was my chief concern with "Skip". When we say "Skip" we really mean "Stop asking me more questions and go with the defaults for things I have not made a decision on." We just need to be sure that when they skip then understand that *our* default options will be chosen.

@jharting I say we rope @ryelo in on this and give a mock up of the ideal state, but move the MR forward with something simple like "Use defaults for the rest".

@ryelo @mattnolting I think it would be cool to see UI that shows the total number of questions we will ask you. How many you have answered, and how many you have not. Then down below the "Skip" button could say "Use defaults (3)" or "Skip (3)". Giving the customer a summarization of what they have done, and what there is to do will help them understand what they are skipping.

We should also take care to communicate that "skipping" is really skipping the question, not the action. The action still takes place with the default procedure.

**Comment by jharting** [comment]
Current status:



In the past the wizard used to have a progress bar (blue dots). I think simply bringing that back could help with "UI that shows the total number of questions we will ask you. How many you have answered, and how many you have not"

Also note that very often the customer is going to be asked a single question only thus we should optimize for that scenario.

**Comment by jharting** [comment]
@Kinlaw @iphands @mattnolting @ryelo so I brought back the navigation dots and changed the wording simply to "Skip and use defaults". Even if the user does not entirely get what it does the first time they see it, they'll learn once they click it :-)

Anyway, unless you have some far better idea about the button wording let's get this merged as the new reboot stuff depends on this. https://github.com/RedHatInsights/insights-frontend/pull/164

**Comment by Kinlaw** [comment]
This looks good to me. I think that if we are going to keep the navigation dots then we should probably make them selectable so that a user can jump back and forth between the options. Maybe not since they can go back and change their choices in the Playbook Summary tab.

@jharting thoughts?

**Comment by jharting** [comment]
@Kinlaw I can do that. If you don't mind let me do that in a separate PR though.

**Comment by iphands** [comment]
Mergin, unless you guys stop me :D

**Comment by Kinlaw** [comment]
@jharting works for me.

**Pull request merged**
