### PR TITLE
Fixed more unportal bugs

### PR DESCRIPTION
**Pull request by ryelo**
Fixes the rest of the bugs on #326 
- Hiding the "Ansible supported" next to the Ansible icon
- System summary background does not overflow
- Added spacing on the maintenance table
- Planner buttons styled
- Give playbook their columns back
- fixing borders on maintenance table
- more planner buttons

### CODE REVIEW

**Comment by jharting** [comment]
@ryelo looks good. I found a few more glitches which I'll add to https://github.com/RedHatInsights/insights-frontend/issues/326

**Comment by ryelo** [comment]
@jharting I'm going to keep adding to this PR if that's okay!

**Comment by jharting** [comment]
@ryelo yes, the Jenkins instance is broken so I would be waiting for the checks to complete first anyway.

**Comment by ryelo** [comment]
Should be closer to par now. The separator line for the columns isn't up and running yet.

**Pull request merged**
