### PR TITLE
Cleaned up policies jade/sass

### PR DESCRIPTION
**Pull request by ryelo**

### CODE REVIEW

**Comment by Kinlaw** [comment]
Looks good to me. @mattnolting whatcha think?

One thing, the summary column on view-policies, when the rows have the same values, there's no visual separation.
screen shot 2018-01-11 at 4 14 13 pm

**Comment by Kinlaw** [comment]
@ryelo beautiful. This looks good to me. I'll leave it for @mattnolting to stamp the final approval since it's a lot of jade structure and css.

**Comment by mattnolting** [comment]
Looking at this today..

**Comment by iphands** [comment]
@mattnolting on a merge crusade... you like changes?

**Comment by iphands** [comment]
@ryelo @mattnolting check merge commit I just made pour favor

**Comment by iphands** [comment]
@jharting since you already looked at tons of these of me... can you look at that last commit?
https://github.com/RedHatInsights/insights-frontend/pull/379/commits/bcc34e236d6d8288e9c2833f1c63c43145e3d730

I think I am all good, but Im unsure (a little under the weather... head cloudy).

**Comment by iphands** [comment]
@mattnolting After your big commit... RuleSummaries replaces/obsoletes RuleSummary right??

If it does please rm RuleSummary. Thanks

**Comment by iphands** [comment]
Moving this to #394

**Pull request closed without merging**
