### PR TITLE
webhook granular event filters and custom certificates

### PR DESCRIPTION
**Pull request by jharting**

### CODE REVIEW

**Comment by jharting** [comment]
screenshot_20171012_112423
screenshot_20171012_112521

@ryelo I am finished with the frontend logic and backend work. Let me know if you want to do some more styling changes in this PR. Personally I think this is good for now and we can revisit especially the "Webhook triggers" section once more filters are available.

**Comment by ryelo** [comment]
Looking at this now, I want to change a few styles for the custom certificates.

**Comment by jharting** [comment]
screenshot_20171013_135914
screenshot_20171013_135939

**Comment by jharting** [comment]
ready for review

**Comment by jharting** [comment]
@Kinlaw I rebased this branch before merging and that somehow dismissed your review although I have no idea how :confused:

**Pull request merged**
